ApplicationApiException:
  type: object
  properties:
    code:
      type: string
      description: Application-specific error code or identifier for the error type.
    message:
      type: string
      description: Human-readable description providing details about the error.