openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
tags:
  - name: exchangeRate
    description: Endpoints for retrieving current exchange rates
  - name: currencyConversion
    description: Endpoints for currency conversion rates
paths:
  /api/v1/exchange-rate:
    $ref: './api/exchange-rate.yaml'
  /api/v1/currency-conversion:
    $ref: './api/currency-convert.yaml'
  /api/v1/currency-conversion-history:
    $ref: './api/currency-convert-history.yaml'